### ISSUE TITLE
Add DC organizer to Maptime org

### ISSUE THREAD

**Issue by geobrando** [maptime/maptime#43]
Could we get one of our DC organizers added to the Maptime Github org?  Handle is nguyenist

Thanks

**Comment by geobrando** [comment]
This repo doesn't seem to get utilized much anymore, so drawing this to the attention of the @maptime/owners

**Comment by almccon** [comment]
Done! Sorry we didn't coordinate about who would do this... sorry it took so long.

**Comment by geobrando** [comment]
Thanks!
